openapi: 3.0.3
info:
  title: Darkwebsearch - GUI API
  version: "1.0.0"
  description: API for receiving search queries from the frontend and forwarding them to the Manager API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: "/"
    description: Relative server URL

paths:
  /gui-search:
    post:
      summary: Receive search query from GUI and forward to Manager API
      operationId: guiSearch
      security:
        - bearerAuth-JWT: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [query]
              properties:
                query:
                  type: string
                  description: Search query entered by the user
      responses:
        "200":
          description: Search query forwarded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                        description:
                          type: string
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  securitySchemes:
    bearerAuth-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT