openapi: 3.0.3
info:
  title: Darkwebsearch - Manager API
  version: "1.0.0"
  description: API for managing search queries and crawled data in Darkwebsearch.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: "/"
    description: Relative server URL — replace with the real base URL when deployed

paths:
  /search:
    post:
      summary: Perform a search query
      operationId: searchQuery
      security:
        - bearerAuth-JWT: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [query]
              properties:
                query:
                  type: string
                  description: Search query text
      responses:
        "200":
          description: Successful search
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                        description:
                          type: string
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /crawl-results:
    post:
      summary: Provide crawled data
      operationId: crawlData
      security:
        - bearerAuth-APIKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [results]
              properties:
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      content:
                        type: string
                      metadata:
                        type: object
      responses:
        "200":
          description: Successful crawl data submission
          content:
            application/json:
              schema:
                type: boolean
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /analyse-results:
    post:
      summary: Provide analysis results
      operationId: analyseData
      security:
        - bearerAuth-APIKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [results]
              properties:
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      jobId:
                        type: string
                      title:
                        type: string
                      description:
                        type: string
                      url:
                        type: string
                      tags:
                        type: array
                        items:
                          type: string
                      legality:
                        type: boolean
      responses:
        "200":
          description: Successful analysis results submission
          content:
            application/json:
              schema:
                type: boolean
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth-APIKey:
      type: http
      scheme: bearer
      bearerFormat: API Key
    bearerAuth-JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT