openapi: 3.0.3
info:
  title: Darkwebsearch - Crawler API
  version: "1.0.0"
  description: API for starting dark web crawls and retrieving crawl status.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: /
    description: Relative server URL — replace with the real base URL when deployed

paths:
  /crawl:
    post:
      summary: Start crawling one or multiple dark web URLs
      operationId: startCrawl
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - addresses
              properties:
                addresses:
                  type: array
                  description: List of dark web addresses to crawl
                  items:
                    type: string
      responses:
        "200":
          description: Crawl jobs started successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - jobIds
                properties:
                  jobIds:
                    type: array
                    description: List of job IDs for the crawl jobs started
                    items:
                      type: string
        "400":
          description: Invalid request payload
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string

  /status/{jobId}:
    get:
      summary: Get the status of a crawl job
      operationId: getSingleCrawlStatus
      security:
        - bearerAuth: []
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
          description: ID of the crawl job to get status for
      responses:
        "200":
          description: Successfully retrieved individual job status
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                    description: ID of the crawl job
                  status:
                    type: string
                    description: Current status (e.g., running, completed, failed)
        "400":
          description: Invalid job ID
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string

  /status:
    get:
      summary: Get status for multiple crawl jobs
      operationId: getCrawlStatuses
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successfully retrieved list of job statuses
          content:
            application/json:
              schema:
                type: array
                description: List of crawl job statuses
                items:
                  type: object
                  properties:
                    jobId:
                      type: string
                      description: ID of the crawl job
                    status:
                      type: string
                      description: Current status (e.g., running, completed, failed)
        "400":
          description: Invalid request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API Key
